# Generated by Django 5.1.5 on 2025-02-03 17:55

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Todo_table',
            fields=[
                ('uid', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('title', models.CharField(max_length=100)),
                ('description', models.CharField(max_length=100)),
                ('category', models.CharField(choices=[('personal', 'Personal Work'), ('office', 'Office Work'), ('creative', 'Creative Work'), ('meeting', 'Meetings & Appointments'), ('health_wellness', 'Health & Wellness'), ('misc', 'Miscellaneous')], default=('personal', 'Personal Work'), max_length=50)),
                ('deadline', models.DateTimeField(max_length=100)),
                ('priority_level', models.CharField(choices=[('Low Priority', 'Non-Urgent'), ('Medium Priority', 'Standard'), ('High Priority', 'Urgent')], default=('Medium Priority', 'Standard'), max_length=50)),
                ('alternative_refernce', models.EmailField(blank=True, max_length=254, null=True)),
                ('user_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_id', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
