# Generated by Django 5.1.5 on 2025-02-03 18:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='todo_table',
            name='is_completed',
            field=models.BooleanField(default=False),
        ),
    ]
