# Generated by Django 5.1.5 on 2025-02-03 18:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0002_todo_table_is_completed'),
    ]

    operations = [
        migrations.AlterField(
            model_name='todo_table',
            name='category',
            field=models.CharField(choices=[('Personal Work', 'Personal Work'), ('Office Work', 'Office Work'), ('Creative Work', 'Creative Work'), ('Meetings & Appointments', 'Meetings & Appointments'), ('Health & Wellness', 'Health & Wellness'), ('Miscellaneous', 'Miscellaneous')], default=('Personal Work', 'Personal Work'), max_length=50),
        ),
    ]
