# Generated by Django 5.1.5 on 2025-02-04 16:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0003_alter_todo_table_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='todo_table',
            name='deadline',
            field=models.DateTimeField(),
        ),
    ]
